### ISSUE TITLE
future of this project

### ISSUE THREAD

**Issue by nnako** [magicstep/ViATc-English#2]
Hi,

I was wondering if there are plans for continuation of this project. As the last changes have been made about three years ago and the current application status seems to be "unfinished", there still seem some things to be done.

May I ask, why you paused / quit the development? Does a todo list exist?

Thanks.
Nnako

**Comment by magicstep** [comment]
Hi Nnako, thanks for the interest, I thought no one else will bother with it.
I've been using the 0.5.4 version for three years now. I love it, it's not perfected but it's enough for me - that's why there were no updates. I can do some simple changes on request. I'm open to discussion what features are most needed. I'm so-so at programming and a beginner with git. I'd be glad for any feedback, criticism and recommendations.
Everyone is welcome to contribute to this project.

TODO: 
- simplify all: the description, the README file, the interface, the installation process
- standardize the shortcuts a bit more so it's more natural to a vim user. (Half of them are hardcoded, and half in the ini file. ) 
- make marks work, currently they don't work at all 

The above list is for the version 0.5.4
The version 0.6 was a completely different approach, I think it's not worth to bother, too much work.
It would be great if both versions have merged into one but it's just a dream.

**Comment by magicstep** [comment]
I'm so-so at programming and a beginner with git.

**Comment by magicstep** [comment]
The above TODO list is for the version 0.5.4
The version 0.6 was a completely different approach, I think it's not worth to bother. 
It would be great if both versions have merged into one but it's just a dream.

**Comment by magicstep** [comment]
Major release of 0.5.5beta. It is enhanced, corrected and simplified. Things that now work:
- marks
- fancy vim rename
- command line

You can download a compiled executable on https://magicstep.github.io/viatc/
However the script version is most likely ahead of the compiled one.
